apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-deployment
  namespace: development
  labels:
    app: pod-info
spec:
  replica: 3
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      containers:
        - name: pod-info-container
          image: patilram/pod-info-app:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limit:
              memory: "128Mi"
              cpu: "500m"        
          ports:
          - cantainerPort: 3000


