apiVersion: v1
kind: service
metadata:
  name: demo-service
  namespace: develoment
spec:
  selector:
    app: pod-info
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  